### ISSUE TITLE
Rapidly increasing solution values

### ISSUE THREAD

**Issue by philw16** [uwhpsc-2016/homework4#13]
I don't know if anybody has run into this problem, but as successive iterations in the time domain are performed the value of my solution vector greatly increases. The final parallel solution has a norm on the order of 1e42. 

I'm very unsure of what would be causing this, and if I remove any array copying at the end of the loop the norms of the loop end up within ~1 of each other. The only thing I could think of is that there is random data from the temp pointer location making it into the solution vector when I copy the arrays as I had that problem in HW2. Any help would be much appreciated.

**Comment by quantheory** [comment]
I think that this is specific to your code, since I see a bug there. You're adding `2*ukt[i]` in the inner loop when you should be subtracting it instead.

**Comment by philw16** [comment]
Yup that did it. Thank you
