### ISSUE TITLE
Bad termination

### ISSUE THREAD

**Issue by natwall27** [uwhpsc-2016/homework4#15]
I continually get an error when I run the tests that says: 

BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES

I created a stand alone program called "mpi_play.c", which is located under homework4-natwall27. At first it also produced the same error, but I found that when I commented out the freeing of the temporary allocations, it ran just fine. By using print statements I saw that the arrays were evolving with the time-steps. I copied over the same code (with adjustments to refactored form) to heat.c, and I continue to the same error. 

I am wondering if there are other debugging methods I might try to resolve this issue. Any ideas?

Thank you.

**Comment by cswiercz** [comment]
Did you manage to find what was wrong?

**Comment by natwall27** [comment]
No, I am getting the same error. I also see my solutions are not accurate and made a new post.
