### ISSUE TITLE
Traceback error from Make for heat.c with parallel code changes. 

### ISSUE THREAD

**Issue by jleskiw** [uwhpsc-2016/homework4#2]
1) I was able to produce the expected serial_heat.png plot, following the  steps given in the homework.

```
$ make lib
```

produces the object file :

```
mpicc -Iinclude -shared src/heat.o -o lib/libhomework4.so
```

-I updated test_homework4.py with the following addition, as per suggestion from issue #1.

```
import matplotlib 
matplotlib.use(‘Agg')
```

```
$ python test_homework4.py
```

produced the expect plots for serial_heat.png, parallel_heat.png

2) I was not able to test my `heat_parallel.c` changes, as I received a `test_homework4.py`
make file traceback error. I believe I followed the steps given in the homework. Please advise.

-made updates to heat_parallel to include use of MPI.
-installed mpi4y

```
$ pip install mpi4pyd
```

-updated `est_homework4.py` to uncomment the parallel code, comment the serial plot command.

```
$ make lib
```

successful

```
$ make test
Traceback (most recent call last):
    from wrappers import *
  File "test_homework4.py", line 13, in <module>
  File “/projects/file_path/homework4-username/homework4/wrappers.py", line 21, in <module>
    from homework4 import (
  File "/projects/file_path/homework4-username/homework4/__init__.py", line 1, in <module>
    raise OSError("You need to compile your homework library using 'make'.")
    from wrappers import *
OSError: You need to compile your homework library using 'make'.
  File "/projects/file_path/homework4-username/homework4/wrappers.py", line 21, in <module>
    raise OSError("You need to compile your homework library using 'make'.")
OSError: You need to compile your homework library using 'make'.
```

**Comment by cswiercz** [comment]
Closing due to duplication #3
